name: CI/CD Pipeline (disabled)

on:
  workflow_dispatch: {}

jobs:
  noop:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This workflow is intentionally disabled. Vercel handles deployments automatically."
